name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend_fastapi/requirements.txt
      - name: Lint (ruff)
        run: ruff check backend_fastapi
      - name: Run tests (pytest)
        run: pytest -q backend_fastapi/tests
